import { useState, useEffect } from 'react'

import './NewTab.css'

export const NewTab = () => {
  const link = 'https://github.com/guocaoyi/create-chrome-ext'

  return (
    <section>
      <span></span>
      <h1>It's time to lock in</h1>
      <a href={link} target="_blank">
        generated by create-chrome-ext
      </a>
    </section>
  )
}

export default NewTab
